### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by qianzui** [Aweme/McImage#6]
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin with type class com.android.build.gradle.AppPlugin has not been used.
        at org.gradle.api.internal.plugins.DefaultPluginContainer.getPlugin(DefaultPluginContainer.java:119)
        at org.gradle.api.plugins.PluginContainer$getPlugin$0.call(Unknown Source)
        at com.smallsoho.mcplugin.image.utils.AndroidUtil.getAndroidExtension(AndroidUtil.groovy:10)
        at com.smallsoho.mcplugin.image.utils.AndroidUtil$getAndroidExtension$0.callStatic(Unknown Source)
        at com.smallsoho.mcplugin.image.utils.AndroidUtil.getMinSdkVersion(AndroidUtil.groovy:16)
        at com.smallsoho.mcplugin.image.utils.AndroidUtil$getMinSdkVersion.call(Unknown Source)
        at com.smallsoho.mcplugin.image.webp.WebpUtils.isPNGConvertSupported(WebpUtils.groovy:17)
        at com.smallsoho.mcplugin.image.webp.WebpUtils$isPNGConvertSupported$0.callStatic(Unknown Source)
        at com.smallsoho.mcplugin.image.webp.WebpUtils.securityFormatWebp(WebpUtils.groovy:52)
        at com.smallsoho.mcplugin.image.webp.WebpUtils$securityFormatWebp.call(Unknown Source)
        at com.smallsoho.mcplugin.image.ImagePlugin$_apply_closure1$_closure2$_closure3$_closure4$_closure5$_closure6$_closure7.doCall(ImagePlugin.groovy:99)
        at com.smallsoho.mcplugin.image.ImagePlugin$_apply_closure1$_closure2$_closure3$_closure4$_closure5$_closure6.doCall(ImagePlugin.groovy:90)
        at com.smallsoho.mcplugin.image.ImagePlugin$_apply_closure1$_closure2$_closure3$_closure4$_closure5.doCall(ImagePlugin.groovy:87)
        at com.smallsoho.mcplugin.image.ImagePlugin$_apply_closure1$_closure2$_closure3$_closure4.doCall(ImagePlugin.groovy:86)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:656)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:637)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 20 more

**Comment by smallSohoSolo** [comment]
需要根目录引入自己的local.properties，放入你的maven参数和gradle参数 检查下是否引入，我本地mac编译没有问题

**Comment by qianzui** [comment]
检测过几次配置应该没问题，后来发现在application中使用没问题，在library的module中使用编译会报这个错误，以前0.0.2的时候library是可以用的。你试一下本地有没有这个问题，我也是mac环境。

**Comment by smallSohoSolo** [comment]
感谢反馈，确实有Bug，已修复，请升级0.1.0版本。

**Comment by smallSohoSolo** [comment]
感谢反馈，确实有Bug，已修复，请升级0.1.1版本。

**Comment by qianzui** [comment]
给力！
